### ISSUE TITLE
insufficient memory?

### ISSUE THREAD

**Issue by weiguangcui** [regonzar/paravt#2]
The code reports an error of insufficient memory:
```
Reading file=31 numthisfile=32594084 skiptype=30704124
Task=  1 Npthistot=531221124
Task=  0 Npthistot=542520700
Read Complete. Nread=1073741824 in 66 blocks of 500000 bytes.
Border size=596.997681 , density=0.000000
Task=1 NumThis=531221124 NumThis_boundary=6345486
Task=0 NumThis=542520700 NumThis_boundary=6464998
Running VT with options: qhull v QJ p Fv
QH6016 qhull error: insufficient memory to project 548985698 points

While executing:  | qhull v QJ p Fv
Options selected for Qhull 2015.1.r 2016/01/03:
  run-id 918084492  voronoi  points  Qbbound-last-qj  Pgood  Fvoronoi
ERROR RUNNING QHULL!!!!!

QH6016 qhull error: insufficient memory to project 537566610 points

While executing:  | qhull v QJ p Fv
Options selected for Qhull 2015.1.r 2016/01/03:
  run-id 918084492  voronoi  points  Qbbound-last-qj  Pgood  Fvoronoi
ERROR RUNNING QHULL!!!!!
```
But the server have more than it requires and paravt only occupied less than 5% of its total memory...
What the problem should be? and How can I solve it?
Thank you!

Weiguang

**Comment by regonzar** [comment]
Hi,
You are processing a huge number of many particles per task, it will take too much time using two task with ~530000000 particles means that a node of your server needs ~  1.6TB of ram only for VT computation. (code uses ~3GB of ram per million particles)

That 5% memory probably is refereed to the total server memory(i dont think 1.6TB is the 5% of a single node memory). 
Which is the total memory of a single node? remember each task run in a single node at most. Check the architecture of your server, how many nodes, processors per node and memory per node.

I recommend you to use a larger number of mpi task 64 or 128, and distribute then in enough nodes to keep memory load within node limits, and run computation fast. (i recommend less than 10millon particles per task for fast computation)

In addition, if still not enough memory you can use the LOWMEMORY parameter in the config file.

see details in reference paper.
https://arxiv.org/abs/1601.06429

**Comment by weiguangcui** [comment]
Hi,

Thanks for clearing this. I didn't know that VT required such a lot of
memory.
I will give a try later and hope that the server with 1Tb memory can handle
this calculation.

Bye,
Weiguang

**Comment by weiguangcui** [comment]
Hi, 
It works fine.  
Thank you!
